# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bluemeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Qweasd123.
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.gmail.com
    username: mateuspinha32@gmail.com
    password: hevzkyxkexiogkep
    from: mateuspinha32@gmail.com
    properties:
      mail.transport.protocol: smtp
      mail.smtp.port: 587
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  flyway:
    locations: classpath:/db/migration/mysql

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO

# =================================
# = RealMeet
# =================================
realmeet:
  allocations:
    maxFilterLimit: 50
  email:
    templates:
      allocationCreated:
        subject: Novo agendamento de sala criado
        templateName: allocation-created.html
      allocationUpdated:
        subject: Agendamento de sala alterado
        templateName: allocation-updated.html
      allocationDeleted:
        subject: Agendamento de sala excluido
        templateName: allocation-deleted.html
      allocationReport:
        subject: Relat√≥rio de Agendameto de Sala
        templateName: allocation-report.html
  reports:
    allocationReport:
      maxMonthsInterval: 12
